import type { Transaction } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: new Date('2024-07-15'),
    description: 'Grocery shopping at Market',
    amount: 75.5,
    currency: 'USD',
    type: 'expense',
    category: 'Groceries',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '2',
    date: new Date('2024-07-15'),
    description: 'Monthly Salary',
    amount: 3000,
    currency: 'USD',
    type: 'income',
    category: 'Income',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '3',
    date: new Date('2024-07-14'),
    description: 'Dinner with friends',
    amount: 45.0,
    currency: 'USD',
    type: 'expense',
    category: 'Dining Out',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '4',
    date: new Date('2024-07-13'),
    description: 'Gas for car',
    amount: 40.0,
    currency: 'USD',
    type: 'expense',
    category: 'Transportation',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '5',
    date: new Date('2024-07-12'),
    description: 'Electricity Bill',
    amount: 120.0,
    currency: 'USD',
    type: 'expense',
    category: 'Utilities',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '6',
    date: new Date('2024-07-10'),
    description: 'Movie tickets',
    amount: 25.0,
    currency: 'USD',
    type: 'expense',
    category: 'Entertainment',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '7',
    date: new Date('2024-07-08'),
    description: 'New T-shirt',
    amount: 30.0,
    currency: 'USD',
    type: 'expense',
    category: 'Shopping',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '8',
    date: new Date('2024-07-05'),
    description: 'Freelance Project Payment',
    amount: 500,
    currency: 'USD',
    type: 'income',
    category: 'Income',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
  {
    id: '9',
    date: new Date('2024-07-01'),
    description: 'Rent Payment',
    amount: 1200,
    currency: 'USD',
    type: 'expense',
    category: 'Rent/Mortgage',
    createdBy: 'mock-user',
    createdByName: 'Mock User',
  },
];
